name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.13.0"
      - name: Install dependencies
        run: npm install
      - name: Migrate DB
        run: npm run migrate --env production

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "560b0c3a-f3aa-4e74-b8fd-263e31b1497e"
          heroku_app_name: "test-deploy-challenge6"
          heroku_email: "jarotsetiawan1001@gmail.com"